apiVersion: v2
name: magda-function-template
description: A Helm chart for Magda Openfaas function
version: "0.0.57-0"
kubeVersion: ">= 1.14.0-0"
home: "https://github.com/magda-io/magda-function-template"
sources: ["https://github.com/magda-io/magda-function-template"]
